### ISSUE TITLE
Finish updating Older Samples to newer format in SamplerApp

### ISSUE THREAD

**Issue by jdub1581** [FXyz/FXyz#1]
A few Samples still need to be re-worked.
All Samples in Composite package need to be updated.

**Comment by Birdasaur** [comment]
SphereSegment migrated to SegmentedDomeMesh sample.

**Comment by Birdasaur** [comment]
Capsule updated with fixes to face/winding pattern. Available currently in following Pull Request:
https://github.com/FXyz/FXyz/pull/18

**Comment by Birdasaur** [comment]
#
