### ISSUE TITLE
OrbitControls sample

### ISSUE THREAD

**Issue by altavir** [FXyz/FXyz#103]
I am back to implementing JavaFX back-end for 3D visualization in physics. I already have working three-js back-end and I want for experience to be similar. Right now I need something similar to https://threejs.org/docs/index.html#examples/en/controls/OrbitControls. Meaning that right mouse button moves the center of view around the central plane of the 3D scene and left mouse button allows to rotate around this point in two directions.

Are there any samples or tools to do so in FXyz or I need to build it from scratch?

**Comment by Birdasaur** [comment]
Let me make sure I understand clearly the effect you want...

1. When a user right clicks and drags you would like the position of the camera to change... ie "pan"?
2. When panning the direction... ie the "rotation" of the camera would remain the same?
3. When a user left clicks and drags you would like the position of the camera to change in an arc?
4. The camera arc would be governed by a distance... "zoom"... and the direction of the drag? 
5. Direction of arc would be some combination of changing Pitch and Yaw?
6. Finally while left clicking... the rotation of the camera would update to always be aimed at a fix point?

**Comment by altavir** [comment]
Something like that. The idea is that "look at" point is always in the same zero x-y plane. Righ mouse button shifts the point in this plane and moves camera alongside the point so the camera angle is not changed. Left mouse button changes the camera angle without changing the camera target so camera is rotated around that point. The wheel changes the distance.

Here is an online example: https://threejs.org/examples/#webgl_animation_cloth

It tried to do it myself, but JavaFX rotation composition is a little bit complicated. Also there is a problem with centering the view. In Javafx the zero coordinate is located in the upper left point of the screen and I need the "look at" point to be in the center. I did not manage to keep it in the center when the panel is resized.

**Comment by Birdasaur** [comment]
What you want is totally doable. I don't think we have that exact demo but all the parts have been implemented here and there. I'll work with you to get it working.  
But first let's first address this coordinate problem you mentioned. That doesn't sound correct for a JavaFX 3D subscene. 0,0 is upper left for a 2D scene but for a 3D subscene the 0,0,0 is in the center relatively speaking.   
How are you defining your subscene and camera?
Do you have this code or a simplified version of it posted online somewhere where I can check it?
Are you performing mouse coordinate conversions from screen to 3D manually? (that shouldn't be necessary.)

**Comment by altavir** [comment]
Here you are: https://github.com/mipt-npm/dataforge-vis/blob/dev/dataforge-vis-spatial/src/jvmMain/kotlin/hep/dataforge/vis/spatial/fx/FXCanvas3D.kt.

The whole application is fully open-source, so you can try it yourself. While our primary target is JS, it would be really nice to finally fix FX version, because it looks nice and much easier to debug.

**Comment by altavir** [comment]
My attempt to implement controls is [here](https://github.com/mipt-npm/dataforge-vis/blob/dev/dataforge-vis-spatial/src/jvmMain/kotlin/hep/dataforge/vis/spatial/fx/OrbitControls.kt), but it does not work in a way, I want it to.

**Comment by Birdasaur** [comment]
I'm not currently setup to run kotlin on this machine but looking at your code it appears you are instantiating your subscene and camera in FXCanvas3D.kt correct. Even though you call it a canvas really its not a javafx Canvas object per say, but a SubScene object right?

**Comment by altavir** [comment]
Yes, I use subscene. I call it canvas to make internal naming more sensible and to use similar naming across platforms.
Also you do not need to set anything up for kotlin, Gradle downloads the plug-in as a part of the build process. I am not sure that dev branch is build able though.

**Comment by Birdasaur** [comment]
@altavir How did this go? Did you resolve your issues?

**Comment by altavir** [comment]
@Birdasaur Not yet. We are focused on JS target and the general release is planned until the end of the year. I do not have time to work on the controls problem, but is more or less the main blocker for JavaFX target (not a lot of work, but I just do not have time for it right now).

**Comment by altavir** [comment]
Implemented in VisionForge dev branch: https://github.com/mipt-npm/visionforge/blob/dev/visionforge-fx/src/main/kotlin/space/kscience/visionforge/solid/OrbitControls.kt

**Comment by Birdasaur** [comment]
@altavir  I'm trying to clean house on the issues so we can produce a new release. Looks like your original issue is resolved, albeit in Kotlin. Congrats. Sorry about the huge lapse in response time. (life :-s )
If you need something along these lines maybe file a new issue with the specifics.
