### ISSUE TITLE
Bug in Skybox.java

### ISSUE THREAD

**Issue by wholder** [FXyz/FXyz#104]
These two lines in `Skybox.java` have the back and front images reversed:

```
        back.setImage(frontImg);
        front.setImage(backImg);

```
It should be:

```
        back.setImage(backImg);
        front.setImage(frontImg);

```
Wayne

**Comment by jdub1581** [comment]
It has been quite a while since I have been here.. Appologies to the Community for my abscence and any possible transgressions. I'll take a look, I believe it was the orientation of this particular image. I probably did not refactor it for that reason.
