### ISSUE TITLE
java beginner needs help

### ISSUE THREAD

**Issue by SirBerny** [FXyz/FXyz#105]
i know its not the right place, but i don't know where else to ask. i was able to download the project and  do ./gradlew assemble and ./gradlew run. 

But i always fail to get the project in eclipse and do the the sample code.

Can anyone instruct me?

**Comment by Birdasaur** [comment]
I'm more of a NetBeans guy  (like 100% a NetBeans guy  ;-)   ) but I can give it a shot.
What steps have you done thus far and what is the current error/problem that you are seeing?

**Comment by SirBerny** [comment]
> 
> 
> I'm more of a NetBeans guy (like 100% a NetBeans guy ;-) ) but I can give it a shot.
> What steps have you done thus far and what is the current error/problem that you are seeing?

thank you birdasaur, i just succeeded to run the the demo. I just made a new project and linked the FXzy libraries in my project. So thanks till next question ...

**Comment by Birdasaur** [comment]
Ok great! Quick question... just curious... are you looking to make a module based project or a traditional classpath project?

**Comment by AlmasB** [comment]
Seems like this issue has been resolved.
