### ISSUE TITLE
Upgrade PolyLine3D

### ISSUE THREAD

**Issue by Birdasaur** [FXyz/FXyz#11]
PolyLine3D currently uses a Ribbon style triangle winding approach to connecting points... A triangle strip is created on top and then a reverse triangle strip is created underneath creating a flat 3D structure. This works and is very efficient in scenes whose polylines have many states, reducing the total number of vertices to be rendered.  The Ribbon algorithm renders 12N vertices and 4N faces per line segment, where a line segment is 2 points.  Unfortunately it treats the z axis as effectively zero so depending on the angle of the camera and the direction of the line segments its possible to rotate the camera such that certain segments of the polyline can appear transparent.
We need to upgrade the PolyLine3D class to allow the user to specify additional triangle strip winding algorithms that provide true 3D depth at the cost of additional vertices/faces.  A Triangle Tube structure would be the minimum 3D structure to achieve this with a cost of an additional 6N + 6 vertices and 2N + 2 faces.  (including start and end caps) 
Width variable should be applied equally to each angle of the triangles.

**Comment by Birdasaur** [comment]
And the good news is I have a functioning solutions which I will clone and commit shortly.

**Comment by Birdasaur** [comment]
#12 
@jperedadnr 
Pull request for PolyLine3D and ControlsFX upgrades

**Comment by runiter** [comment]
Hi, when I used PolyLine3D the line has x and y thickness but no z thickness when I use these parameters:

```new PolyLine3D(points, 0.1f, Color.WHITE, PolyLine3D.LineType.TRIANGLE)```

![image](https://user-images.githubusercontent.com/3038088/205815631-e55df9cf-1dc4-4fbc-8a1b-c46b552970a4.png)

Looks like this PR was supposed to fix this but it didn't. Or am I doing something wrong?

**Comment by Birdasaur** [comment]
I'll have to try it in a simple test... but it could be simply that the math used to calculate the "Z vertex" of each triangle does not do well when you use extremely small width values. You have 0.1 as the width so the expectation is that each side of each triangle renders as 0.1. 
Down in the weeds PolyLine3D has a for loop attempting to calculate the vertices of a 3D triangle (not the triangles of the TriangleMEsh) based on your list of points.

```
        //For each data point add three mesh points as an equilateral triangle
        float half = new Float(width / 2.0);
        for(Point3D point: points) {
            //-0.288675f*hw, -0.5f*hw, -0.204124f*hw,
            mesh.getPoints().addAll(point.x - 0.288675f*half, point.y - 0.5f*half, point.z - 0.204124f*half);
            //-0.288675f*hw, 0.5f*hw, -0.204124f*hw, 
            mesh.getPoints().addAll(point.x - 0.288675f*half, point.y + 0.5f*half, point.z - 0.204124f*half);
            //0.57735f*hw, 0f, -0.204124f*hw
            mesh.getPoints().addAll(point.x + 0.57735f*half, point.y + 0.5f*half, point.z - 0.204124f*half);
        }
```
All we are trying to do here is roughly center the point you provide within that triangle. The reason for using a triangle is that when rendered in 3D it gives an appearance of thickness but with the least cost (in terms of TriangleMesh vertices and faces... which are different triangles). It looks like when you use very small width values that the current offsets just don't provide enough separation.

I'm guessing that we need to adjust the offsets themselves to better center it.  Its been a while since I wrote this so I'll need some time to mess with it.

**Comment by runiter** [comment]
I tried with larger width value and noticed same problem.
Even in the code you posted above it seems that the z value is always the same (point.z - 0.204124f*half)
So based on your code I'm not surprised that there is no z thickness.
Shouldn't there be a flip of + to - somewhere in the z level calculation?
