### ISSUE TITLE
error: module not found: jdk.scripting.nashorn

### ISSUE THREAD

**Issue by Suicolen** [FXyz/FXyz#115]
i cloned the repo, opened it in IntelliJ and built it, however im getting this error
error: module not found: jdk.scripting.nashorn
on module-info.java (FXyz-Samples) at the 44th line requires jdk.scripting.nashorn;
NOTE: im using java 15, could it be because of that?

**Comment by Birdasaur** [comment]
I am experience the same issue using OpenJDK 15 and Apache NetBeans 12.1 so its likely not an issue with the IDE.

**Comment by Birdasaur** [comment]
Oh duh... the reason is because jdk.scripting.nashorn was deprecated in previous version of Java and removed as of 15. So this:

   requires jdk.scripting.nashorn;

Which is used for our Sampler is "the problem"

**Comment by jperedadnr** [comment]
Indeed, JDK 15 has removed the Nashorn engine. There was already an issue open for this: https://github.com/FXyz/FXyz/issues/59

We need to replace it with GraalVM JS engine, but that will take some work.

**Comment by Birdasaur** [comment]
"So long Nashorn... we hardly knew ye."

Should we create an issue to migrate to JDK/JFX 15?

**Comment by jperedadnr** [comment]
https://github.com/FXyz/FXyz/issues/59
