### ISSUE TITLE
[Solved] Skybox memory leak

### ISSUE THREAD

**Issue by ivanstepanovftw** [FXyz/FXyz#133]
Solved by commenting `startTimer();` in Skybox.java

**Comment by jperedadnr** [comment]
Can you clarify the issue and how to reproduce it?

**Comment by ivanstepanovftw** [comment]
> PhD Structural Engineer, Java Champion, Oracle Dev Champion. Love coding Java & JavaFX, mobile apps, IoT. Software Engineer at http://gluonhq.com/

**Comment by ivanstepanovftw** [comment]
```
for (i in 1..10000) {
node.getChildren().add(new Skybox());
}
```

**Comment by ivanstepanovftw** [comment]
Not solved, why are you closing https://github.com/FXyz/FXyz/blob/master/FXyz-Core/src/main/java/org/fxyz3d/scene/Skybox.java

**Comment by ivanstepanovftw** [comment]
Add method to stop the timer or remove it completely

**Comment by Birdasaur** [comment]
Or you submit a PR to add the additional functionality you desire.
Last I checked we don't work for you.
