### ISSUE TITLE
Error when running the sample code

### ISSUE THREAD

**Issue by DanielAndrei1** [FXyz/FXyz#134]
Hello,

The following error appears when running the sample code:
FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\Users\Dany\AppData\Local\Temp\ijresolvers.gradle' line: 256

* What went wrong:
Execution failed for task ':Sample:Sample.main()'.
> Could not resolve all files for configuration ':Sample:runtimeClasspath'.
   > Could not find org.jzy3d:jzy3d-jdt-core:1.0.2.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jzy3d/jzy3d-jdt-core/1.0.2/jzy3d-jdt-core-1.0.2.pom
       - https://repo.maven.apache.org/maven2/org/jzy3d/jzy3d-jdt-core/1.0.2/jzy3d-jdt-core-1.0.2.pom
     Required by:
         project :Sample > org.fxyz3d:fxyz3d:0.5.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
![image](https://user-images.githubusercontent.com/44091613/109399046-3c327000-7938-11eb-8be3-16df82bb6eaa.png)
![image](https://user-images.githubusercontent.com/44091613/109399014-14430c80-7938-11eb-9902-b267783fe20d.png)
![image](https://user-images.githubusercontent.com/44091613/109399024-1c02b100-7938-11eb-84cf-18bc8e1c4460.png)

Can I get some help, please?

Thanks,
Daniel

**Comment by jperedadnr** [comment]
Yes, long story short: 
Just add the jzy3d repo:
```
repositories {
    mavenCentral()
    maven {
        url = "http://maven.jzy3d.org/releases"
    }
}
```

Long story: we tried to fix this issue by publishing that to the pom (https://github.com/FXyz/FXyz/pull/100), but Gradle doesn't resolve repositories, only Maven.

I've just updated the readme's sample to include that missing repository.

**Comment by DanielAndrei1** [comment]
Hi Jose,

Many thanks for this!

Kind regards,
Daniel
