### ISSUE TITLE
Compile errors in Eclipse after initial import

### ISSUE THREAD

**Issue by armin-reichert** [FXyz/FXyz#146]
After cloning the FXyz repository and importing the Gradle projects into Eclipse (Version: 2021-03 (4.19.0), I get compile errors in project FXyz-Importers (in the unit tests). 

I can fix this issue in Eclipse by adding "requires org.junit.jupiter.api;" to the module-info file and adding the JUnit5 library to the Eclipse Modulepath. 

But then the Gradle build from the command-line fails:
error: module not found: org.junit.jupiter.api

What does that mean?

There is also another compile error in FXyz-Samples:

The type com.sun.javafx.scene.CameraHelper is not accessible	RayShooting.java

**Comment by Birdasaur** [comment]
Just pushed an update from @jperedadnr that bumps many of the dependencies up including Gradle to 7.6 and JDK to 17. Please see if this helps with the issue you are seeing.
Regarding the RayShooting example, I just opened a branch to fix that: https://github.com/FXyz/FXyz/tree/154-rayshooting-needs-update

The RayShooting problem is unrelated to the junit dependency issue and is covered already in #154

**Comment by armin-reichert** [comment]
I can now run `gradlew assemble` (using gradle 7.6). inside a console window and get no compile errors anymore 

However, after importing the gradle projects inside Eclipse (version 2022-12), there are still compile errors in the unit test classes. Maybe this is a problem with missing modularisation support of Junit5, but this is just a guess. The JUnit classes cannot be resolved, they are on the classpath of the imported Gradle project, maybe they should be on the module path, I don't know.
