### ISSUE TITLE
Colors problem

### ISSUE THREAD

**Issue by Jfranz25** [FXyz/FXyz#147]
Dear FXyz,

I'm working on a project with large Pointcloud files in JavaFX. After tests it's seem that FXyz is the best 3D control for this project.
Especially for displaying thoushands points with the possibilty to pick elements.

In order to maintain the application updated, i'm trying to migrate the project from Java 8 to Java 11. After this process i'm not able to correctly display a ScatterMesh with different colors.

Below you will find 2 screenshots, the first one is Java8 and the second one Java11

Java8 https://ibb.co/2dnLZtj
Java11 https://ibb.co/LxvFWKd

The colors are defined through  an intensity value  (mesh.setTextureModeVertices3D(1023,p->p.f, 0, 1023);.
As you cann see on screenshots the colors are displayed correctly in Java8, the 'f' value used for each point. In java 11 the intensity values not seems to be used. The code is the same for the 2 versions (excepted the red displayed label).

I guess the problem is linked to the light of the scene (AmbientLight or PointLight). I tried to add some light but it doesn't work.

Do you have an idea to correctly display points in java 11 ?

Best regards

**Comment by Birdasaur** [comment]
Hey... sorry about letting a half a year go by.  :-(
Did you ever resolve this issue? If not, are you able to share enough of a code snippet where one of us could debug?
