### ISSUE TITLE
Adding Axis & Labels to group

### ISSUE THREAD

**Issue by ThomasDaheim** [FXyz/FXyz#151]
Hi,

after some trial and error I managed to make progress to now show a map based on SRTM data together with tracks on this map (some documentation would surely be helpful...):

![image](https://user-images.githubusercontent.com/14020617/150422470-d359c600-d532-4ca4-a401-60c6ee895ddb.png)

Now I would want to add axis & label text for better orientation - similar to this:

![image](https://user-images.githubusercontent.com/14020617/150422700-4114193a-dcc8-4c02-9718-2da662aca77d.png)

How would I do this most efficiently? I definitely wouldn't want to add 3d-Text.. My idea would be to e.g. create axis using standard 2d-Charts (that would give me all the options to set tics, label formats, ...) and somehow "insert" the axis at the right location in the group (hoping that would take care of things like rotation, ...).

BUT I have no good idea how this could be achieved or if there is a better way. Any pointers to code (fragments) would be welcome! I would be willing to share any solution I can come up with :-)

BTW: is there any better place to ask this kind of "how-to" questions? Because I still have 2-3 more of that kind...

**Comment by Birdasaur** [comment]
Hey there Thomas. Thanks for doing such cool stuff with our library. We're happy to help. I suppose here is as good a place as any. :-)

I think the most efficient way to do what you want here would be to extend from our Floating Labels  example:
https://github.com/FXyz/FXyz/blob/master/FXyz-Samples/src/main/java/org/fxyz3d/samples/utilities/FloatingLabels.java

What it does is place 2D labels over the 3D SubScene and translate them around on the screen based on the location of a 3D point.  The implementation in that example also has some simple screen edge clipping logic for when the 3D point goes outside the camera view. (this prevents the 2D labels from being translated off screen and thereby stretching the SubScene.)

I've used it to create a labeled grid a lot like what you actually want:
https://www.youtube.com/watch?v=1jScsuI5_Uc

The trick with the FloatingLabels example is that I actually add a very tiny little sphere wherever I want a floating label. Then I manage a hashmap of these little sphere's against the labels... transforming the label position whenever the 3D scene camera is changed. To do that I scattered the updateLabels() call in the various keyboard and mouse event handlers. Not sure if that is the most efficient or elegant way to do it... but it works just fine. (Maybe there is event related to camera view or frustrum change we could hook instead... not sure)

Also not sure if you really need a 3D node in the scene to do this or if you could actually do it with a synthetic point. Never really mattered for any of my examples.

**Comment by ThomasDaheim** [comment]
So, finally had some spare time on my hands to play around with this. Axis line & tic marks are fine now:

![Clipboard02](https://user-images.githubusercontent.com/14020617/151616188-9c42bc99-9b67-42f3-adae-196fb9d01288.jpg)

But I'm really struggling to make sense of how the labels are handled in your example. From what I read:

- labels are created and added to a separate group that has is not affected by any rotation of the `nodeGroup`
- in case of movement of the nodes their location is projected into the x/y plane of the subscene
- labels are moved to the proper x/y coordinates of the subscene

Is that the general idea? That the labels are not 3D objects but merely track the (projected) movement of their nodes?

**Comment by ThomasDaheim** [comment]
BTW, if my understanding with the labels is correct: Could I also use the same to draw the lines? I'm not too happy with the Cylinders since I would need to resize thickness based on range of data shown - otherwise they appear to thick or thin...

**Comment by Birdasaur** [comment]
>the labels are not 3D objects but merely track the (projected) movement of their nodes

Yup. Its annoying that there isn't access to a direct buffer text writer like in OpenGL but having a hashmap and some transform code isn't bad at all.

> BTW, if my understanding with the labels is correct: Could I also use the same to draw the lines? I'm not too happy with the Cylinders since I would need to resize thickness based on range of data shown - otherwise they appear to thick or thin...

Yes sorta. True any 2D node could be moved based on a point3d location on the screen using this technique. 
I'm not 100% sure about how lines would end up though. I THINK it should be fine but you would have to manage both ends of the line with a separate point3d in your hashmap. I do think it would work though.

**Comment by ThomasDaheim** [comment]
Will stick with the Cylinders for now. One problem at a time :-)

**Comment by ThomasDaheim** [comment]
![Clipboard02](https://user-images.githubusercontent.com/14020617/151855482-2dc18166-1287-433c-8778-bb584735ad91.jpg)

Thanks for the pointer, @Birdasaur
