### ISSUE TITLE
Closed 3D Convex Hull example

### ISSUE THREAD

**Issue by Birdasaur** [FXyz/FXyz#152]
Hey fellow FXyz3D'ers. @jperedadnr @jdub1581 @AlmasB @
I have a 3D point cloud data set. I would like to generate a Mesh which represents the 3D convex hull of the point cloud. To get the hull, I'm using QuickHull3D. It seems to be working and provides me with a set of vertices and a set of face indexes.

Now that I have my hull of vertices... which FXyz3D mesh type would be the best choice?  
At first I thought maybe SurfaceMesh but it doesn't close the shape by default... which creates a weird height map layout. (which is what it is designed to do so...).

My ideal Mesh would be closed all around but I'm ok if there are winding gaps... its only for visual analysis.

**Comment by jperedadnr** [comment]
Here is a little hint: https://github.com/FXyz/FXyz/tree/master/FXyz-Core/src/main/java/org/fxyz3d/shapes/primitives/helper/delaunay

that is used from a Surface3DMesh
https://github.com/FXyz/FXyz/blob/master/FXyz-Core/src/main/java/org/fxyz3d/shapes/primitives/Surface3DMesh.java#L91

In theory that would create a mesh out of your 3D points.

**Comment by Birdasaur** [comment]
ahhh... good idea. Let me look into it.

**Comment by Birdasaur** [comment]
same scene without the Surface3DMesh
![image](https://user-images.githubusercontent.com/4649925/150595335-1ffbe669-fb54-4428-983b-df4967635430.png)

**Comment by Birdasaur** [comment]
Same scene but I've reduced the scatter mesh point size to a very small value so the vertex locations  (white spheres) show well.

![image](https://user-images.githubusercontent.com/4649925/150596019-2303b436-1b67-4464-9680-60fd13d8a531.png)

Based on this I believe my quick hull is working (good enough for what I'm trying to do). However it appears like the triangle winding doesn't like the order I'm providing?

**Comment by Birdasaur** [comment]
Oh ugh... DelauneyMesh isn't exported yet... @jperedadnr was this a hint from you that I should get off my butt push a code update?  ;-)

**Comment by jperedadnr** [comment]
What do you mean?
> DelauneyMesh isn't exported yet
The code is two years old, it should be in any recent release?

**Comment by Birdasaur** [comment]
yes... you seem to be correct:
https://github.com/FXyz/FXyz/blob/master/FXyz-Core/src/main/java/module-info.java
Yet my Maven dependency says I'm using 0.5.4... ?? Still investigating...

**Comment by jperedadnr** [comment]
See the javadoc from the code that actually does the Delaunay triangulation: https://github.com/FXyz/FXyz/blob/master/FXyz-Core/src/main/java/org/fxyz3d/shapes/primitives/helper/delaunay/jdt/DelaunayTriangulation.java#L35

I'm not sure if a complex 3D set of scattered unordered points are suitable for this...
I recall using it for some "smooth" 3D set of points coming out of a math function.

Latest release is 0.5.4, indeed, but you are right:
```exports org.fxyz3d.shapes.primitives.helper.delaunay;```
is missing from that list (and maybe `exports org.fxyz3d.shapes.primitives.helper.delaunay.jdt` too)

Can you try adding `--add-exports` to your project?

**Comment by Birdasaur** [comment]
oh dang I missed the extra delaunay package name. Thats it then.
I think I have to add this to my maven compiler plugin as compiler args yes? For example
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>11</release>
                    <compilerArgs>
                      <arg>--add-exports</arg>
                      <arg>org.fxyz3d.core/org.fxyz3d.shapes.primitives.helper.delaunay=ALL-UNNAMED</arg>
                    </compilerArgs>                    
                </configuration>
            </plugin>
```

**Comment by Birdasaur** [comment]
oh wow I'm using version 6... I'm way behind. Updated to 0.0.8 and added your options.
Reloaded pom... still says invisible. :-( 

Here is the relevant section of my Pom:
```

            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <configuration>
                    <options>
                        <o>--add-exports=org.fxyz3d.core/org.fxyz3d.shapes.primitives.helper.delaunay=ALL-UNNAMED</o>
                    </options>                    
                    <mainClass>${mainClassName}</mainClass>
                    <includePathExceptionsInClasspath>true</includePathExceptionsInClasspath>
                </configuration>
```

**Comment by Birdasaur** [comment]
Looking at DelaunayTriangulation.java:

> The application main use is 3D surface (terrain) presentation.

Am I doomed from the start trying to use this particular implementation? After a bit of reading it seems like I need an "enclosed triangulation" ?  Any thoughts?

**Comment by jperedadnr** [comment]
I've put together this quick test, on how you can create a MeshView out of a Delaunay triangulation from a set of 3D points:

```
import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.PerspectiveCamera;
import javafx.scene.Scene;
import javafx.scene.SceneAntialiasing;
import javafx.scene.paint.Color;
import javafx.scene.paint.PhongMaterial;
import javafx.scene.shape.CullFace;
import javafx.scene.shape.DrawMode;
import javafx.scene.shape.MeshView;
import javafx.scene.shape.TriangleMesh;
import javafx.stage.Stage;
import org.fxyz3d.geometry.Point3D;
import org.fxyz3d.shapes.primitives.helper.delaunay.DelaunayMesh;
import org.fxyz3d.shapes.primitives.helper.delaunay.Triangle3D;

import java.util.ArrayList;
import java.util.List;

public class DelaunayTest extends Application {

    private final int size = 600;
    private TriangleMesh mesh;

    private List<Point3D> getPointsForGauss() {
        List<Point3D> result = new ArrayList<>();
        for (double x = -300.0; x <= 300.0; x += 10.0) {
            for (double y = -300.0; y <= 300.0; y += 10.0) {
                result.add(new Point3D(x, x * x + y * y, y));
            }
        }
        return result;
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void init() {
        DelaunayMesh delaunayMesh = new DelaunayMesh(getPointsForGauss());

        mesh = new TriangleMesh();
        for (Point3D point : delaunayMesh.getNormalizedPoints()) {
            mesh.getPoints().addAll((float) (point.getX() * size), (float) (-1. * point.getY() * size), (float) (point.getZ() * size));
        }
        for (Point3D point : delaunayMesh.getNormalizedPoints()) {
            mesh.getTexCoords().addAll((float) (point.getX()), (float) (point.getZ()));
        }
        List<Point3D> normalizedPoints = delaunayMesh.getNormalizedPoints();
        for (Triangle3D triangle : delaunayMesh.getTriangle3DList()) {
            int faceIndex1 = normalizedPoints.indexOf(triangle.getP0());
            int faceIndex2 = normalizedPoints.indexOf(triangle.getP1());
            int faceIndex3 = normalizedPoints.indexOf(triangle.getP2());
            mesh.getFaces().addAll(faceIndex1, faceIndex1, faceIndex2, faceIndex2, faceIndex3, faceIndex3);
        }
    }

    @Override
    public void start(Stage stage) {
        PerspectiveCamera camera = new PerspectiveCamera();
        camera.setTranslateZ(-size);

        MeshView meshView = new MeshView(mesh);
        meshView.setTranslateY(size);
        PhongMaterial material = new PhongMaterial(Color.RED);
        meshView.setMaterial(material);
        meshView.setDrawMode(DrawMode.LINE);
        meshView.setCullFace(CullFace.NONE);
        Scene scene = new Scene(new Group(meshView), 600, 600, true, SceneAntialiasing.BALANCED);
        scene.setCamera(camera);
        stage.setScene(scene);
        stage.show();
    }
}
```

It gives something like:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/2043230/150620308-490ffa98-e385-4a50-85b3-41b2f4f3dbcf.png">

Hope it helps!

**Comment by Birdasaur** [comment]
Dang nice!  Do you think the order of the List<Point3D> matters for the triangulation algorithm?

**Comment by Birdasaur** [comment]
I manually copied the delaunay package into my local project to get around the visibility issue.  Here is what I produced using your mesh making utility:

![image](https://user-images.githubusercontent.com/4649925/150621827-9a59f095-dfdb-4149-b6d5-75379643ccbe.png)

Its performing similar to how the Surface3DMesh did. I suspect that the order of the points matters, so I added labels to each point.  Notice the vertices 0, 1 and 2 locations... they are the first three verts returned by my the QuickHull 3D algorithm.
Could this be the problem?

**Comment by Birdasaur** [comment]
Using http://quickhull3d.github.io/quickhull3d/ for the algorithm.

**Comment by jperedadnr** [comment]
Sorting has some effects...
I've added `Collections.shuffle(result);`, and the mesh is the visually similar, the triangulation is different:

initial order

![image](https://user-images.githubusercontent.com/2043230/150639183-644d2173-461a-4ce4-b252-42a19ab43536.png)

shuffled

![image](https://user-images.githubusercontent.com/2043230/150639171-d3b629c1-29ee-47b2-990d-f07be2512ae9.png)

**Comment by Birdasaur** [comment]
I am trying to understand the differences between your example and mine. Since you shuffled... order isn't necessarily the primary problem. Could it be that the triangulation works well for points that are along a plane (albeit bulging like in your example) but not well in an enclosed set?  My points are randoms between 0 and 1 for the sake of testing which results in a Hull that forms a cubic polyhedra.  Could it be that the triangulation algorithm doesn't do well with enclosed polyhedra like that?

Or maybe specifying the first point to start from could have a significant effect? (like maybe I need to ensure that the first point is not an edge case corner point?)

**Comment by Birdasaur** [comment]
I wrote some code to export the hull points as a hardcoded array if you wanted to try to import them and see what I mean. The array below has a stride of 3... x, y, z.
I artificially scaled the 0 to 1 values by 1000 in order to see the resulting mesh which looks like this:
![image](https://user-images.githubusercontent.com/4649925/150642672-34841008-a7e9-4707-bb7b-13b76172ebfd.png)

hull points that produced it:

`double [] factors = new double[] { 980.3112, 575.61523, 562.3446, 886.1211, 5.957078, 174.87918, 806.89557, 996.1836, 50.98289, 569.3182, 724.2613, 958.6487, 975.3372, 291.6086, 103.313515, 93.25487, 770.19885, 204.91808, 499.98254, 199.0293, 810.64874, 936.00616, 839.4431, 735.08966, 191.95903, 866.3352, 258.83072, 134.88828, 39.42591, 402.848, 971.86725, 838.5228, 140.60992, 207.54433, 624.80273, 983.45087, 247.5533, 914.40393, 303.2152, 157.24434, 590.245, 845.912, 862.72144, 991.2504, 770.5367, 782.3539, 749.8092, 825.27954, 339.72424, 903.20575, 993.8668, 786.6158, 500.78574, 747.422, 454.75827, 2.3348956, 418.8025, 421.89935, 159.06726, 772.3678, 972.5792, 130.19934, 159.82016, 362.3727, 404.80255, 945.6708, 87.801636, 607.3077, 534.3643};
`

**Comment by jperedadnr** [comment]
I'm doing `x, z, y`, seems to work better.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/2043230/150646203-7aa03660-8b92-405a-8de7-b32a0698a50f.png">

[DelaunayTest.java.txt](https://github.com/FXyz/FXyz/files/7918693/DelaunayTest.java.txt)

**Comment by Birdasaur** [comment]
Interesting... this could partially be an artifact of the inverted Y Axis in the fx 3D system?
Looking at the DelaunayTriangulation class it seems this algorithm is well suited to a surface extended from a plane.  I wonder if we could make (at least for my case but maybe generally) a "EnclosedTriangulation" as a multiphased delaunay?

1. We make the general assumption of a bounding box cubic form
1. Request Delauney Triangulation "over the top" half of the points
1. Request a second Delauney "below the bottom half of the points
1. Merge the two meshes?

**Comment by Birdasaur** [comment]
tried this powercrust algorithm but it didn't seem to work as advertised.
https://github.com/meiXXI/PointCloudCrust

Other folks on the internet are saying that a way to do this is to split the north and south "hemispheres" of the point cloud and then project them to a 2D plane. Then run the delaunay on that projection. When the 3D surface is created, roll the two hemisphere's back together. Likely will need to have a custom triangle stitching at the join point but it should be "close enough"

**Comment by Birdasaur** [comment]
Was able to implement using https://github.com/Quickhull3d/quickhull3d
Worked like a charm. Highly recommended.
