### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by jimbok8** [FXyz/FXyz#19]
I have added your code to Netbeans.
The only way to get this to build successfully was to separately download the LICENSE file and add this to the source code.
However, I am quite ignorant when it comes to gradle - so it is probably my fault! So this is just to let you know in case it is a real problem.

**Comment by jperedadnr** [comment]
The LICENSE file was added to the root project, but not to the subprojects, and this led to an error when running the `build` task.

**Comment by jperedadnr** [comment]
Solved with PR #27
