### ISSUE TITLE
PolyLine3D width should be float

### ISSUE THREAD

**Issue by jimbok8** [FXyz/FXyz#23]
The width of the line in PolyLine3D should be specified as a float, since this is the 'units' of the coordinates.
Forcing the line  to be an int is not correct for small geometries specified with points of the magnitude of 1.0f.

**Comment by Birdasaur** [comment]
Philosophically you are correct and reviewing the code I cannot see a reason why this field remains an int. I believe it was something that nobody has ever complained about and so never was changed.
Will work on a PR that addresses the issue soon.

**Comment by Birdasaur** [comment]
#18 PR updates class to use float for width. New constructors utilize float.
Old int width constructors Deprecated and convert int parameter to float value.

**Comment by jperedadnr** [comment]
Fixed with PR #18
