### ISSUE TITLE
Create setCenter method for spherical shapes

### ISSUE THREAD

**Issue by jimbok8** [FXyz/FXyz#24]
Having used CuboidMesh and its setCenter method I was surprised that SpheroidMesh does not have this method.
I think there is a case for all meshes with symmetry having a setCenter method.
What do you think?

**Comment by jperedadnr** [comment]
Can't you use `SegmentedSphereMesh` instead? It has a center property, and it is textured.

**Comment by Birdasaur** [comment]
Closing due to age. Please request reopen if disagreed.
