### ISSUE TITLE
Linux feedback

### ISSUE THREAD

**Issue by wefwefwe** [FXyz/FXyz#3]
Hi, just tried FXyz-Samples-1.0-all on my Linux laptop
my system is: 
CPU: Intel Core i3-4005U Processor (3M Cache, 1.70 GHz)
GPU: Intel HD graphics 4400 GPU - Intel Haswell Mobile
http://ark.intel.com/products/75105
4 GB DDR3 1600 MHz ×1 Ram 
Linux ver: 3.16.7-21-desktop - 64bit - OpenSUSE 13.2 Gnome

i'm using oracle's jdk version jdk-8u45-linux-x64
javafx.runtime.version=8.0.45
Platform.isSupported(ConditionalFeature.SCENE3D): returns true

~/>java -Dprism.verbose=true:
Prism pipeline init order: es2 sw 
Using java-based Pisces rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2 succeeded.
GLFactory using com.sun.prism.es2.X11GLFactory
(X) Got class = class com.sun.prism.es2.ES2Pipeline
Initialized prism pipeline: com.sun.prism.es2.ES2Pipeline

when i run the sample it works good littel slow but it works i get:
Initialising FXyz-Sampler sample scanner...
    Discovering projects...
        Found project 'FXyz-Samples', with sample base package 'org.fxyz.samples'
ERROR: Class name: ding.When
ERROR: Initial filename: javafx/beans/binding/When.class
ERROR: Class name: ding.StringExpression
ERROR: Initial filename: javafx/beans/binding/StringExpression.class
ERROR: Class name: ding.StringBinding
ERROR: Initial filename: javafx/beans/binding/StringBinding.class
ERROR: Class name: ding.SetExpression
ERROR: Initial filename: javafx/beans/binding/SetExpression.class
ERROR: Class name: ding.SetBinding
ERROR: Initial filename: javafx/beans/binding/SetBinding.class
ERROR: Class name: ding.ObjectExpression
ERROR: Initial filename: javafx/beans/binding/ObjectExpression.class
ERROR: Class name: ding.ObjectBinding
ERROR: Initial filename: javafx/beans/binding/ObjectBinding.class
ERROR: Class name: ding.NumberExpressionBase
ERROR: Initial filename: javafx/beans/binding/NumberExpressionBase.class
ERROR: Class name: ding.NumberExpression
ERROR: Initial filename: javafx/beans/binding/NumberExpression.class
ERROR: Class name: ding.NumberBinding
ERROR: Initial filename: javafx/beans/binding/NumberBinding.class
ERROR: Class name: ding.MapExpression
ERROR: Initial filename: javafx/beans/binding/MapExpression.class
ERROR: Class name: ding.MapBinding
ERROR: Initial filename: javafx/beans/binding/MapBinding.class
ERROR: Class name: ding.LongExpression
ERROR: Initial filename: javafx/beans/binding/LongExpression.class
ERROR: Class name: ding.LongBinding
ERROR: Initial filename: javafx/beans/binding/LongBinding.class
ERROR: Class name: ding.ListExpression
ERROR: Initial filename: javafx/beans/binding/ListExpression.class
ERROR: Class name: ding.ListBinding
ERROR: Initial filename: javafx/beans/binding/ListBinding.class
ERROR: Class name: ding.IntegerExpression
ERROR: Initial filename: javafx/beans/binding/IntegerExpression.class
ERROR: Class name: ding.IntegerBinding
ERROR: Initial filename: javafx/beans/binding/IntegerBinding.class
ERROR: Class name: ding.FloatExpression
ERROR: Initial filename: javafx/beans/binding/FloatExpression.class
ERROR: Class name: ding.FloatBinding
ERROR: Initial filename: javafx/beans/binding/FloatBinding.class
ERROR: Class name: ding.DoubleExpression
ERROR: Initial filename: javafx/beans/binding/DoubleExpression.class
ERROR: Class name: ding.DoubleBinding
ERROR: Initial filename: javafx/beans/binding/DoubleBinding.class
ERROR: Class name: ding.BooleanExpression
ERROR: Initial filename: javafx/beans/binding/BooleanExpression.class
ERROR: Class name: ding.BooleanBinding
ERROR: Initial filename: javafx/beans/binding/BooleanBinding.class
ERROR: Class name: ding.Bindings
ERROR: Initial filename: javafx/beans/binding/Bindings.class
ERROR: Class name: ding.Binding
ERROR: Initial filename: javafx/beans/binding/Binding.class
ERROR: Class name: com.sun.prism.null3d.DummyTexturePool
ERROR: Initial filename: com/sun/prism/null3d/DummyTexturePool.class
ERROR: Class name: com.sun.prism.es2.WinGLPixelFormat
ERROR: Initial filename: com/sun/prism/es2/WinGLPixelFormat.class
ERROR: Class name: com.sun.prism.es2.WinGLFactory
ERROR: Initial filename: com/sun/prism/es2/WinGLFactory.class
ERROR: Class name: com.sun.prism.es2.WinGLDrawable
ERROR: Initial filename: com/sun/prism/es2/WinGLDrawable.class
ERROR: Class name: com.sun.prism.es2.WinGLContext
ERROR: Initial filename: com/sun/prism/es2/WinGLContext.class
ERROR: Class name: com.sun.prism.es2.MonocleGLPixelFormat
ERROR: Initial filename: com/sun/prism/es2/MonocleGLPixelFormat.class
ERROR: Class name: com.sun.prism.es2.MonocleGLFactory
ERROR: Initial filename: com/sun/prism/es2/MonocleGLFactory.class
ERROR: Class name: com.sun.prism.es2.MonocleGLDrawable
ERROR: Initial filename: com/sun/prism/es2/MonocleGLDrawable.class
ERROR: Class name: com.sun.prism.es2.MonocleGLContext
ERROR: Initial filename: com/sun/prism/es2/MonocleGLContext.class
ERROR: Class name: com.sun.prism.d3d.D3DVramPool
ERROR: Initial filename: com/sun/prism/d3d/D3DVramPool.class
ERROR: Class name: com.sun.prism.d3d.D3DPipeline
ERROR: Initial filename: com/sun/prism/d3d/D3DPipeline.class
ERROR: Class name: com.sun.javafx.iio.ios.IosImageLoader
ERROR: Initial filename: com/sun/javafx/iio/ios/IosImageLoader.class
ERROR: Class name: com.sun.javafx.font.coretext.CTGlyph
ERROR: Initial filename: com/sun/javafx/font/coretext/CTGlyph.class
ERROR: Class name: ding.StringFormatter
ERROR: Initial filename: com/sun/javafx/binding/StringFormatter.class
ERROR: Class name: ding.StringConstant
ERROR: Initial filename: com/sun/javafx/binding/StringConstant.class
ERROR: Class name: ding.SetExpressionHelper
ERROR: Initial filename: com/sun/javafx/binding/SetExpressionHelper.class
ERROR: Class name: ding.SelectBinding
ERROR: Initial filename: com/sun/javafx/binding/SelectBinding.class
ERROR: Class name: ding.ObjectConstant
ERROR: Initial filename: com/sun/javafx/binding/ObjectConstant.class
ERROR: Class name: ding.MapExpressionHelper
ERROR: Initial filename: com/sun/javafx/binding/MapExpressionHelper.class
ERROR: Class name: ding.LongConstant
ERROR: Initial filename: com/sun/javafx/binding/LongConstant.class
ERROR: Class name: ding.Logging
ERROR: Initial filename: com/sun/javafx/binding/Logging.class
ERROR: Class name: ding.ListExpressionHelper
ERROR: Initial filename: com/sun/javafx/binding/ListExpressionHelper.class
ERROR: Class name: ding.IntegerConstant
ERROR: Initial filename: com/sun/javafx/binding/IntegerConstant.class
ERROR: Class name: ding.FloatConstant
ERROR: Initial filename: com/sun/javafx/binding/FloatConstant.class
ERROR: Class name: ding.ExpressionHelperBase
ERROR: Initial filename: com/sun/javafx/binding/ExpressionHelperBase.class
ERROR: Class name: ding.ExpressionHelper
ERROR: Initial filename: com/sun/javafx/binding/ExpressionHelper.class
ERROR: Class name: ding.DoubleConstant
ERROR: Initial filename: com/sun/javafx/binding/DoubleConstant.class
ERROR: Class name: ding.ContentBinding
ERROR: Initial filename: com/sun/javafx/binding/ContentBinding.class
ERROR: Class name: ding.BindingHelperObserver
ERROR: Initial filename: com/sun/javafx/binding/BindingHelperObserver.class
ERROR: Class name: ding.BidirectionalContentBinding
ERROR: Initial filename: com/sun/javafx/binding/BidirectionalContentBinding.class
ERROR: Class name: ding.BidirectionalBinding
ERROR: Initial filename: com/sun/javafx/binding/BidirectionalBinding.class
ERROR: Class name: com.sun.glass.ui.win.WinWindow
ERROR: Initial filename: com/sun/glass/ui/win/WinWindow.class
ERROR: Class name: com.sun.glass.ui.win.WinView
ERROR: Initial filename: com/sun/glass/ui/win/WinView.class
ERROR: Class name: com.sun.glass.ui.win.WinTimer
ERROR: Initial filename: com/sun/glass/ui/win/WinTimer.class
ERROR: Class name: com.sun.glass.ui.win.WinTextRangeProvider
ERROR: Initial filename: com/sun/glass/ui/win/WinTextRangeProvider.class
ERROR: Class name: com.sun.glass.ui.win.WinSystemClipboard
ERROR: Initial filename: com/sun/glass/ui/win/WinSystemClipboard.class
ERROR: Class name: com.sun.glass.ui.win.WinPixels
ERROR: Initial filename: com/sun/glass/ui/win/WinPixels.class
ERROR: Class name: com.sun.glass.ui.win.WinMenuImpl
ERROR: Initial filename: com/sun/glass/ui/win/WinMenuImpl.class
ERROR: Class name: com.sun.glass.ui.win.WinMenuDelegate
ERROR: Initial filename: com/sun/glass/ui/win/WinMenuDelegate.class
ERROR: Class name: com.sun.glass.ui.win.WinMenuBarDelegate
ERROR: Initial filename: com/sun/glass/ui/win/WinMenuBarDelegate.class
ERROR: Class name: com.sun.glass.ui.win.WinGestureSupport
ERROR: Initial filename: com/sun/glass/ui/win/WinGestureSupport.class
ERROR: Class name: com.sun.glass.ui.win.WinDnDClipboard
ERROR: Initial filename: com/sun/glass/ui/win/WinDnDClipboard.class
ERROR: Class name: com.sun.glass.ui.win.WinCursor
ERROR: Initial filename: com/sun/glass/ui/win/WinCursor.class
ERROR: Class name: com.sun.glass.ui.win.WinCommonDialogs
ERROR: Initial filename: com/sun/glass/ui/win/WinCommonDialogs.class
ERROR: Class name: com.sun.glass.ui.win.WinChildWindow
ERROR: Initial filename: com/sun/glass/ui/win/WinChildWindow.class
ERROR: Class name: com.sun.glass.ui.win.WinApplication
ERROR: Initial filename: com/sun/glass/ui/win/WinApplication.class
ERROR: Class name: com.sun.glass.ui.win.WinAccessible
ERROR: Initial filename: com/sun/glass/ui/win/WinAccessible.class
ERROR: Class name: com.sun.glass.ui.swt.SWTWindow
ERROR: Initial filename: com/sun/glass/ui/swt/SWTWindow.class
ERROR: Class name: com.sun.glass.ui.swt.SWTView
ERROR: Initial filename: com/sun/glass/ui/swt/SWTView.class
ERROR: Class name: com.sun.glass.ui.swt.SWTRobot
ERROR: Initial filename: com/sun/glass/ui/swt/SWTRobot.class
ERROR: Class name: com.sun.glass.ui.swt.SWTMenuDelegate
ERROR: Initial filename: com/sun/glass/ui/swt/SWTMenuDelegate.class
ERROR: Class name: com.sun.glass.ui.swt.SWTCursor
ERROR: Initial filename: com/sun/glass/ui/swt/SWTCursor.class
ERROR: Class name: com.sun.glass.ui.swt.SWTClipboard
ERROR: Initial filename: com/sun/glass/ui/swt/SWTClipboard.class
ERROR: Class name: com.sun.glass.ui.swt.SWTApplication
ERROR: Initial filename: com/sun/glass/ui/swt/SWTApplication.class
ERROR: Class name: com.sun.glass.ui.swt.CustomTransfer
ERROR: Initial filename: com/sun/glass/ui/swt/CustomTransfer.class
ERROR: Class name: com.sun.glass.ui.monocle.X11WarpingCursor
ERROR: Initial filename: com/sun/glass/ui/monocle/X11WarpingCursor.class
ERROR: Class name: com.sun.glass.ui.monocle.X11Screen
ERROR: Initial filename: com/sun/glass/ui/monocle/X11Screen.class
ERROR: Class name: com.sun.glass.ui.monocle.X11InputDeviceRegistry
ERROR: Initial filename: com/sun/glass/ui/monocle/X11InputDeviceRegistry.class
ERROR: Class name: com.sun.glass.ui.monocle.X11Cursor
ERROR: Initial filename: com/sun/glass/ui/monocle/X11Cursor.class
ERROR: Class name: com.sun.glass.ui.monocle.X11AcceleratedScreen
ERROR: Initial filename: com/sun/glass/ui/monocle/X11AcceleratedScreen.class
ERROR: Class name: com.sun.glass.ui.monocle.X
ERROR: Initial filename: com/sun/glass/ui/monocle/X.class
Project [ name: FXyz-Samples, sample count: 16, tree:  Sample [ sampleName: FXyz-Samples, children: [ Sample [ packageName: Utilities, children: [ Sample [ sampleName: SkyBoxing, children: [] ],  Sample [ sampleName: RayIntersections, children: [] ],  Sample [ sampleName: Billboarding, children: [] ]] ],  Sample [ packageName: Shapes, children: [ Sample [ packageName: Texturedmeshes, children: [ Sample [ sampleName: SurfacePlot, children: [] ],  Sample [ sampleName: Springs, children: [] ],  Sample [ sampleName: SegmentedTorus, children: [] ],  Sample [ sampleName: Prisms, children: [] ],  Sample [ sampleName: Knots, children: [] ],  Sample [ sampleName: Icosahedron, children: [] ],  Sample [ sampleName: CurvedSpring, children: [] ],  Sample [ sampleName: Cuboids, children: [] ],  Sample [ sampleName: BezierMeshes, children: [] ]] ],  Sample [ packageName: Compound, children: [ Sample [ sampleName: ScatterPlotMeshes, children: [] ],  Sample [ sampleName: ScatterPlotColors, children: [] ],  Sample [ sampleName: PolyLines3D, children: [] ],  Sample [ sampleName: Histograms, children: [] ]] ]] ]] ] ]
nodes: 8, faces: 12
nodes: 26, faces: 48
nodes: 98, faces: 192
nodes: 30060, faces: 60000
nodes: 42, faces: 80
nodes: 162, faces: 320
nodes: 642, faces: 1280
nodes: 10000, faces: 20000

**Comment by sanklamm** [comment]
Same on a Mac. Almost none of the samples work. I thought it was on my end.

**Comment by Birdasaur** [comment]
Whoa. I did not realize there was an issue. I can test on a Mac soon.  What version of the JDK are you using on your Mac?

**Comment by sanklamm** [comment]
So I'm using Java version 1.8.0_121.
What I did was cloning the repo, building with Gradle command line tool, opening the project in IntelliJ and trying to run the various runnable classes.

Running `FXyzSample` (or `FXyzSampleBase`) yields the following
```
Exception in Application constructor
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Unable to construct Application instance: class org.fxyz3d.FXyzSampleBase
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:907)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:819)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Process finished with exit code 1
```
Some examples don't work as well.

Due to the lack of documentation I'm not sure if I'm doing something wrong on my end. The minimal example from the GitHub Readme does work though. But it would be easier to get started if you'd mention the maven dependency to just use your project.

If I can provide you with more info, I'd be happy to do so.

I really like this project but I'm having a hard time to get started with it (I'm pretty new to JavaFX).

**Comment by Birdasaur** [comment]
This is enough info. We use NetBeans 8.2... technically it shouldn't matter with a gradle project but you never know. (I think what you did was correct) So in the meantime you could try that while I test it on a mac I have access to.
Agreed that there isn't much documentation (and honestly you won't get any unless a sponsor were to step forward, this was a labor of love) but in spite of that I don't believe the error you are seeing is an issue with the FXyz code.  I think the RuntimeException is a "JavaFX on Mac" type problem... possibly with the sampler framework we used, possibly in instantiated the 3D accelerated scenegraph itself.
Will try today.

**Comment by Birdasaur** [comment]
I couldn't replicate your issue on the Mac Pro I have access to.  Everything just works as expected.  Here are the steps I took:

1. Clone Fxyz using NetBeans 8.2
2. Open the four gradle projects (assumes you have installed the Gradle plugin)
3. Wait for the IDE to prime the projects
4. Assemble FXyz-Core (click on project node -> tasks -> assemble)
5. Assemble FXyz-Client
6. Assemble FXyz-Samples  
7. Run Samples project.

**Comment by sanklamm** [comment]
Thank you for the feedback. The lacking documentation isn't a knock on you. I understand that takes time and functionality is more important.  
I will try and replicate what you did and report back.

**Comment by Birdasaur** [comment]
Were you ever able to replicate our process or move beyond your error state?
The latest PR provides several updates to the gradle build files which also may help.
