### ISSUE TITLE
CameraTransformer - Override setTranslateX(),  setTranslateY() setTranslateZ()

### ISSUE THREAD

**Issue by jimbok8** [FXyz/FXyz#31]
I have been exploring CameraTransformer:
Should this class also include these overridden methods:
setTranslateX(double x) { t.setX(x); }
setTranslateY(double y) { t.setY(y); }
setTranslateZ(double z) { t.setZ(z); }
this would avoid confusion with the original methods of Node.
I am thinking this is would be similar to: these methods
public void setRotateX(double x) { rx.setAngle(x); } etc

**Comment by Birdasaur** [comment]
No longer perceived as needed. Please reopen if disagreed.
