### ISSUE TITLE
Update Compatibility levels to 11

### ISSUE THREAD

**Issue by nlisker** [FXyz/FXyz#43]
Is there a reason source and target compatibilities are still on 1.8 or 1.9?

**Comment by jperedadnr** [comment]
The reason for having FXyz-Core and FXyz-Importers under 1.8 is to allow the use for those that are still using Java 8 (i.e mobile). Note that we are not keeping a branch for 8 (it was discussed but we decided to go with one default master). Since there are no breaking changes, and these artifacts work with Java 8 to 11,  I see no reason for setting levels to 11, or am I missing something?

**Comment by nlisker** [comment]
I'm not sure, but these are my concerns:
1. Since JavaFX 11 supports Java 10 or 11, setting compatibility to less than 10 can break compilation.
2. There are now 2 copies of JavaFX, one an explicit dependency and one implicitly included in the (Oracle) JDK. This can cause issues when running with an IDE. I didn't test this thoroughly but we had those problems already when working on JavaFX itself.

**Comment by jperedadnr** [comment]
I'm not sure if I really understand the possible issues here, but you say that by setting target 1.8 we are setting a dependency in a 1.8 JDK? I'd think that it you have a JDK between 8 and 11 you could run a JavaFX project with it from your IDE or command line, I don't see how can it break compilation?

And if that's the case, what would you propose? Set level to 10? What about support for 8 then?

**Comment by nlisker** [comment]
I'll ask it this way: if JavaFX uses, or will use, language features from Java10+, wouldn't setting source and target compatibility to 1.8 cause issues?

**Comment by jperedadnr** [comment]
Ok, I see. But that didn't happen so far for 10 or 11, did it? There are no language features from 10+ added to the JavaFX core as far as I now.

Only if some time in the future, something is back ported to JavaFX 10/11 adding language features only available in 10+, that could break all the frameworks and libraries out there that use JavaFX and have compatibility set to 8/9? 

At that (extreme) point we could release a new artifact, of course, so still I don't see a problem here.

**Comment by jperedadnr** [comment]
I'm working from my IDE, I never had those issues. Can you tell me how I can reproduce them?

**Comment by nlisker** [comment]
Using Eclipse 4.9, the build path uses Java 9 and the compiler compliance level is set to 9.

The class `org.fxyz3d.samples.utilities.RayShooting` has an error on 

    import com.sun.javafx.scene.CameraHelper;

> The type com.sun.javafx.scene.CameraHelper is not accessible

Similarly, `FloatingLabels` gives these errors on

    import com.sun.javafx.scene.NodeHelper;
    import com.sun.javafx.scene.SceneUtils;

Additionally, launching `org.fxyz3d.client.FXyzClient#main` gives this window:

![image](https://user-images.githubusercontent.com/37422899/47955513-0f593280-dfa2-11e8-8113-d449a6b34231.png)

and this output 

```
Initialising FXyz-Sampler sample scanner...
	Discovering projects...
	Error: Did not find any projects!
[]
```

**Comment by jperedadnr** [comment]
I guess that depends on your eclipse.ini settings. For instance on Windows I have Eclipse 4.9 with `-vm` set to 1.8 and I can't even compile from Eclipse the Client module, as it requires 9. If I try to set `-vm` to JDK-11, Gradle Tasks doesn't work. Obviously it works fine from command line.

What vm option do you have, 1.9? Can you add some vmargs like `--permit-illegal-access`?

**Comment by nlisker** [comment]
My `eclipse.ini` doesn't have a `-vm` setting. I believe it defaults to `%JAVA_HOME%` which is JDK-11.

Adding `--permit-illegal-access` under `-vmargs` doesn't change anything.

Gradle works fine (using Buildship) in any case. It's setting the execution environemnt to 1.9 which points to a JDK-9. (Though now I noticed a new issue in the `buile.gradle` file of Client on the line `apply from: 'gradle/publishing.gradle'` saying "Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10-all.zip'. A problem occurred evaluating script." Don't know when that appeared first.)

**Comment by nlisker** [comment]
In Eclipse 4.11 the publishing `apply from: 'gradle/publishing.gradle'` line does not cause any issues.

Closing as the question has already been answered.
