### ISSUE TITLE
Publish to MavenCentral

### ISSUE THREAD

**Issue by jperedadnr** [FXyz/FXyz#55]
So far artifacts are only published to Bintray

**Comment by AlmasB** [comment]
Any ETA for this?

**Comment by jperedadnr** [comment]
I've noticed I can publish to Maven Central from Bintray directly.

It just requires an extra step after `bintrayUpload`, publish to JCenter and sync to Maven Central, but it works. Artifacts are already available: https://search.maven.org/search?q=org.fxyz3d 
(importers will be ready tomorrow probably)
