### ISSUE TITLE
Public access to the meshes in Text3DMesh

### ISSUE THREAD

**Issue by miho** [FXyz/FXyz#6]
Ironically, the Text3DMesh class does not give access the actual mesh(es). To use it in JCSG, we currently have to utilize ugly reflection hacks to get access to the mesh list.

**Comment by jperedadnr** [comment]
Have you tried `Text3DMesh::getMeshFromLetter` ? That will return the `TexturedMesh` for each letter.

**Comment by miho** [comment]
Sure, but it only gives the the first occurrence of the letter and I need the transformation you apply to each to correctly create the complete mesh. The other method that allows me to access each occurrence seems overly complicated.

**Comment by jperedadnr** [comment]
So you'll need `public List<TexturedMesh> getMeshes()` or alike?

**Comment by miho** [comment]
Exactly, here's my pull request: https://github.com/FXyz/FXyz/pull/7

**Comment by miho** [comment]
Jose, thanks for merging. Issue resolved :)
