### ISSUE TITLE
Add Y up / down property to FXyz sampler

### ISSUE THREAD

**Issue by AlmasB** [FXyz/FXyz#62]
The model in the sample is imported upside down. I have also tried to import a different `.obj` file, the result is also upside down. Is there a bug in the obj importer?

**Comment by jperedadnr** [comment]
No, no bug, but actually there was an [option](https://github.com/javafxports/openjdk-jfx/blob/develop/apps/samples/3DViewer/src/main/java/com/javafx/experiments/jfx3dviewer/ContentModel.java#L146) in the 3DViewer app to use Y up or down. It is the usual problem with JavaFX Y axis...
An easy solution is adding this property as well to the FXyz sampler, so it can be controlled when importing different models.

**Comment by jperedadnr** [comment]
Fixed with #78
