### ISSUE TITLE
MtlReader ignores "Ka" - ambient color

### ISSUE THREAD

**Issue by AlmasB** [FXyz/FXyz#65]

**Comment by nlisker** [comment]
I'm refactoring `MtlReader`. `Ka` is not something `PhonMaterial` supports. How did you want to address it?

**Comment by AlmasB** [comment]
I think we can emulate this. A material is applied to a collection of
faces, this collection is a mesh view with the material parsed as
PhongMaterial.

We can create a Group, put the mesh view inside and add AmbientLight with
the color read from Ka. Afaik the light will be applied to that Group and
its children.

**Comment by nlisker** [comment]
But `Ka` determines the reflection from existing ambient lighting. If there is no `AmbientLight` in the scene then `Ka` doesn't do anything. What you are trying to simulate is an emissive (or self-illumination) color, which should be added to `PhongMaterial`.

**Comment by AlmasB** [comment]
Ah. Didn't know that. So does that mean there is no other way to make use of Ka? In which case we can close this.

**Comment by nlisker** [comment]
The `PhongMaterial` implementation is rather basic. There is a lot it doesn't support.
