### ISSUE TITLE
Suggestion to remove AbstractLoopService

### ISSUE THREAD

**Issue by AlmasB** [FXyz/FXyz#68]
[AbstractLoopService](https://github.com/FXyz/FXyz/blob/master/FXyz-Core/src/main/java/org/fxyz3d/concurrent/AbstractLoopService.java) feels out of place. Also:

1. Users are much better off using the native JavaFX `Application` and `AnimationTimer`
2. As I understand FXyz is a library and not a framework. We shouldn't force any code flow model. Users pull in FXyz as a library to load 3D models and otherwise enhance and / or simplify JavaFX 3D capabilities.

**Comment by jperedadnr** [comment]
FXyz Core was created to provide advanced JavaFX 3D features, mainly in terms of more complex 3D shapes. Importers are new to the project.

You are not forced to use anything from this library.  In fact, the class you mentioned is not used at all. Note that many of the features were experiments...

There is a similar implementation of an `ScheduledService` in `org.fxyz3d.shapes.complex.cloth.ClothMesh`. There are a few videos of this, in case you haven't seen it in action: 
https://www.youtube.com/watch?v=Zx47_vkAP6g
See comment:
> This was using AnimationTimer, so performance was not that great. Later updates I switched to a ScheduledService that almost doubled performance
or https://www.youtube.com/watch?v=NlkWaDvFOK0
or https://www.youtube.com/watch?v=uRsCcpbsdsg

**Comment by AlmasB** [comment]
Huh. I'm interested in investigating why ScheduledService offers more performance.
