### ISSUE TITLE
Duplicate classes with OpenJFX com.sun.javafx.geom

### ISSUE THREAD

**Issue by nlisker** [FXyz/FXyz#71]
`org.fxyz3d.utils.geom` copies classes from the internal `com.sun.javafx.geom`, such as `Vec3f`. It's probably better to access the internal class than keep copies of these.

We could also put in a request for public API.

**Comment by jperedadnr** [comment]
I don't see a solution for this now. 

I'd rather keep out of private API even at the cost of duplicating classes. 

I don't think `com.sun.javafx.geom` is going to change that much anytime soon, and honestly I don't think any of the hidden gems in that package are going to make it to a public package.

**Comment by nlisker** [comment]
> I'd rather keep out of private API even at the cost of duplicating classes.

Alright, then the issue can be closed.

> I don't think any of the hidden gems in that package are going to make it to a public package.

If there are useful things in internal packages I could work on making them public.
