### ISSUE TITLE
Ignored cases of start-of-line whitespaces in Mtl and Obj readers

### ISSUE THREAD

**Issue by nlisker** [FXyz/FXyz#79]
The mtl and obj readers use `startsWith` to parse lines. Is it legal for these files to start a line with a whitespace and then have the relevant info?

```
    # comment
         // <--- some spaces
  new newmtl dents
Ka 0.6 0.6 0.6
   Kd 1 1 1
```

If yes, we need to `trim` the line before parsing.

**Comment by AlmasB** [comment]
I couldn't find any online material referring to that, but given how easy a fix this is we should probably do it.

**Comment by nlisker** [comment]
I'll do it as part of #81.
