### ISSUE TITLE
Sampler window should be resizable

### ISSUE THREAD

**Issue by jperedadnr** [FXyz/FXyz#84]
Also, there is an issue when maximizing it.

**Comment by AlmasB** [comment]
@jperedadnr I've just skimmed through FXyzClient and it appears that the window is essentially `SimpleWindowFrame`. Is there a reason why we can't just use `Stage` itself?

**Comment by jperedadnr** [comment]
Well, it is how it was designed initially (probably even from ControlsFX sampler), but there is also [commented out code](https://github.com/FXyz/FXyz/blob/master/FXyz-Client/src/main/java/org/fxyz3d/client/SimpleWindowFrame.java#L215) with a possible resizing implementation, that for some reason I can't recall was disabled.
Instead of changing the client, I'd rather reenable this code.

**Comment by AlmasB** [comment]
Other than the amount of work needed to redesign the client to use the standard `Stage`, there is no strong reason to stay with current approach? In which case, I would be happy to redesign the client to use `Stage` directly. I think, ultimately, this redesign will lead to less code.

**Comment by jperedadnr** [comment]
At the contrary, I don't see compelling reasons now to do a full redesign of the client. There are "historic" reasons to keep it as it, but of course, it is open to fixes and improvements. I'd rather spend time on the core, the importers, the samples...
