### ISSUE TITLE
Polyline3D Question

### ISSUE THREAD

**Issue by ljramones** [FXyz/FXyz#86]
This is more of a question. I needed to have the ability to draw 3D lines. 
I am writing an application with JavaFX that imports star maps and produces 3D stellar charts of them in space. I have the draw portion for the stars (relative sizes based on type).
What I needed to do and could not was to create a projection plane and draw a line from each star to the plane (sits at y=0) to show its position on the z-axis. I found the drawing of these lines to be difficult in regular JavaFX. So I turned to your library.
Basically, I wanted to use Polyline3D to create a series of distinct line segments (from star to the y=0 plane).  So I make the assumption that I could create all of these segments in a group and add it tot he scene.
Like this:
{
....
       // iterate over all the stars to draw corresponding line segments
        Group lineGroup = new Group();
        for (Node node : stellarGroup.getChildren()) {
            float xFrom = (float) node.getTranslateX();
            float yFrom = (float) node.getTranslateY();
            float zFrom = (float) node.getTranslateZ();

            PolyLine3D lineSegment = drawLineToPlane(xFrom, yFrom, zFrom);
            lineGroup.getChildren().add(lineSegment);
        }
        // stellar group is the set of all stars
        this.getChildren().add(stellarGroup);
        // line gorup are the lines from the star to the plane 
        this.getChildren().add(lineGroup);
    }

    private PolyLine3D drawLineToPlane(float xFrom, float yFrom, float zFrom) {
        float planeY = 0f;
        List<Point3D> linesegment = createLineSegment(xFrom, yFrom, zFrom, planeY);
        return new PolyLine3D(linesegment, 1.0f, Color.WHITE);
    }

    private List<Point3D> createLineSegment(float xFrom, float yFrom, float zFrom, float planeY) {
        Point3D fromPoint = new Point3D(xFrom, yFrom, zFrom);
        Point3D toPoint = new Point3D(xFrom, planeY, zFrom);
        List<Point3D> linesegment = new ArrayList<>();
        linesegment.add(fromPoint);
        linesegment.add(toPoint);
        return linesegment;
    }

So unless I have completely misunderstood, this is how it should work since I just want a set of to/from points.
Of course, once I add this code, the mini Sphere objects seem to disappear (but their labels are present)

**Comment by Birdasaur** [comment]
Hello Evil!  Based on what I can see from your code, and what you have described... the PolyLine3D class should accomplish what you are looking for.  It is intended to automatically build a mesh that connects a list of points... ie.. more than 2 but the way you are using it is fine!  Are you seeing issues with it?  I'm not sure yet what you mean by "the mini sphere objects seem to disappear"...
I don't know what type of Node objects your stellarGroup will hold but be advised you may see some minor issues with "centering" of the Shape3D objects with the PolyLine3D objects. It depends on how that shape3D is translated... ie..  you are using the Translation values to get a starting point, which is fine, but not all Shape3D nodes out there use a local origin at its geometric center.  Some use the upper left most point of the geometry... etc.  
I'm happy someone is using the PolyLine... it would be righteous to see screenshots of your results.

**Comment by Birdasaur** [comment]
@EvilJinious1  are you still seeing issues with your example or were you able to resolve?  If so I will close the question.

**Comment by JamesPeters98** [comment]
I seem to be having a similar issue!
Any objects that are textured seem to lose their texture after I add the PolyLine to the group!
Using the sample PolyLine class this is the before and after:

Before the PolyLine is added to the Group
![](https://i.gyazo.com/3ac368e83c3b9657d1e34c15cc22bd36.png)

And after:
![](https://i.gyazo.com/0b61fe05fdf49632b71de791ccaadb8c.png)

```
public class Earth extends Body {

    private static final double RADIUS = 6371; //KM

    private static final double MAP_WIDTH  = 8192 / 2d;
    private static final double MAP_HEIGHT = 4092 / 2d;

    private static final String DIFFUSE_MAP =
            "earth/earth_gebco8_texture_8192x4096.jpg";
    private static final String NORMAL_MAP =
            "earth/earth_normalmap_flat_8192x4096.jpg";
    private static final String SPECULAR_MAP =
            "earth/earth_specularmap_flat_8192x4096.jpg";

    public Earth(String name, double radius, double x, double y, double z) {
        super(name, radius, x, y, z);
        PhongMaterial earthMaterial = new PhongMaterial();

        earthMaterial.setDiffuseMap(
                new Image(
                        this.getClass().getClassLoader().getResourceAsStream(DIFFUSE_MAP),
                        MAP_WIDTH,
                        MAP_HEIGHT,
                        true,
                        true
                )
        );
        earthMaterial.setBumpMap(
                new Image(
                        this.getClass().getClassLoader().getResourceAsStream(NORMAL_MAP),
                        MAP_WIDTH,
                        MAP_HEIGHT,
                        true,
                        true
                )
        );
        earthMaterial.setSpecularMap(
                new Image(
                        this.getClass().getClassLoader().getResourceAsStream(SPECULAR_MAP),
                        MAP_WIDTH,
                        MAP_HEIGHT,
                        true,
                        true
                )
        );

        setMaterial(earthMaterial);
    }

    public Earth(double x, double y, double z){
        this("Earth", RADIUS, x,y,z);
    }
}
```

**Comment by Birdasaur** [comment]
In all my deep space trajectory design tools I never saw this effect but I also had all my trajectories (Polyline3D objects) in their own group. 
Have you tried adding all polyline3d objects to their own group and if so does the same effect occur?
