### ISSUE TITLE
Hotfix to exclude slf4j-simple supporting Java 8

### ISSUE THREAD

**Issue by calvertdw** [FXyz/FXyz#87]
We use Log4j2 and get the following annoyance when running with fxyz3d 0.1.1 on our classpath.

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Duncan/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.11.1/4b41b53a3a2d299ce381a69d165381ca19f62912/log4j-slf4j-impl-2.11.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Duncan/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.6.1/58e59bfb3e247097b8122243b3bfe0049c8cfae8/slf4j-simple-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
```
The transitive comes from `jcsg`.
![image](https://user-images.githubusercontent.com/1161586/53846790-e9ee2c80-3f73-11e9-94f1-b21eac55ce4b.png)

We currently still use Java 8, so it appears a hotfix to 0.3.0 would be appropriate. Would this be something you guys could do? I'm also open to forking and releasing the hotfix myself.

Tagging @SylvainBertrand

**Comment by jperedadnr** [comment]
Actually FXyz has two dependencies in `eu.mihosoft.vrl.jcsg:jcsg` and `org.orbisgis:poly2tri-core`, and both use `org.slf4j`.

I see that you [use](https://github.com/ihmcrobotics/ihmc-javafx-toolkit/blob/758360ad5a1cc5248e9425c502cc0b11ffd84b2d/src/main/java/us/ihmc/javaFXToolkit/text/Text3D.java) the `Text3D` shape from FXyz, which relies on Poly2tri, which at the end has the dependencies on slf4j (see for instance [Polygon](https://github.com/orbisgis/poly2tri.java/blob/master/poly2tri-core/src/main/java/org/poly2tri/geometry/polygon/Polygon.java#L10)).

So this is something we can't change.

However if you do something like:
```
compile("org.fxyz3d:fxyz3d:0.3.0") {
    exclude group: 'org.slf4j', module: 'slf4j-simple'
}
``` 
you will keep the `slf4j-api` required dependency, but you will remove the slf4j binding.

Have you tried it?

**Comment by calvertdw** [comment]
Unfortunately the Gradle `exclude group` does not affect the publication. So when we publish our library that uses yours, the undesired `slf4j-simple` artifact will be pulled in by our users.

I think we might be able to inject the exclusion into the published `*.pom`.

**Comment by calvertdw** [comment]
To be clear, having `slf4j-api` on the classpath is fine! Which I think is not used (or shouldn't be used) by your code. 😄

**Comment by jperedadnr** [comment]
We don't use it directly, but as I mentioned it is part of Poly2tri. 

While we could publish a version where we remove this transitive dependency, at this point I think it is better if you can do that, in your publishing task.

For the next versions we'll do it, but we are on 11 as you know.

**Comment by Birdasaur** [comment]
Calvertdw a new version, 0.5.0, was just pushed. This is the first all modular release, which would help solve this problem for you if you have migrated to a modular build. Are you still using JDK 8 at this time?  Did you solve the transitive dependency problem yet?

**Comment by calvertdw** [comment]
@Birdasaur That is extremely cool. Hopefully we will get there too sometime soon. I think we are okay for now. I will close this issue.
