### ISSUE TITLE
Implement or remove org.fxyz3d.client.HeaderMenu

### ISSUE THREAD

**Issue by AlmasB** [FXyz/FXyz#94]
[This file](https://github.com/FXyz/FXyz/blob/master/FXyz-Client/src/main/java/org/fxyz3d/client/HeaderMenu.java) does not seem to be used at the moment, including its associated fxml file. This should either be implemented into the project or removed.

**Comment by jperedadnr** [comment]
Probably can be removed (including FXML file), we did a few experiments back in the day, not everything ended up being used though.
